/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import About_button from "./script/About_button"
import About_checkBox from "./script/About_checkBox"
import About_clip from "./script/About_clip"
import About_list from "./script/About_list"
import Item from "./script/Item"
import About_progressBar from "./script/About_progressBar"
import About_radio from "./script/About_radio"
import About_slider from "./script/About_slider"
import About_text from "./script/About_text"
import CallDialogControl from "./script/CallDialogControl"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/About_button.js",About_button);
		reg("script/About_checkBox.js",About_checkBox);
		reg("script/About_clip.js",About_clip);
		reg("script/About_list.js",About_list);
		reg("script/Item.js",Item);
		reg("script/About_progressBar.js",About_progressBar);
		reg("script/About_radio.js",About_radio);
		reg("script/About_slider.js",About_slider);
		reg("script/About_text.js",About_text);
		reg("script/CallDialogControl.js",CallDialogControl);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "about_list.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
