/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var CLASS$=Laya.class;
var STATICATTR$=Laya.static;
var View=laya.ui.View;
var Dialog=laya.ui.Dialog;
var Scene=Laya.Scene;
if(!window.ui) window.ui={};
var RankUI=(function(_super){
		function RankUI(){
			
			RankUI.__super.call(this);
		}
		CLASS$(RankUI,'ui.RankUI',_super);
		var __proto__=RankUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.createView(RankUI.uiView);
		}
		RankUI.uiView={"type":"View","props":{"width":600,"height":600},"compId":2,"child":[{"type":"List","props":{"width":600,"name":"list","height":400},"compId":3,"child":[{"type":"Box","props":{"width":600,"renderType":"render","name":"item","height":80},"compId":4,"child":[{"type":"Image","props":{"y":0,"x":0,"width":600,"skin":"img/panelBK.png","sizeGrid":"20,20,20,20","name":"bk","height":80},"compId":6},{"type":"Label","props":{"y":15,"x":5,"width":60,"text":"0","name":"ranking","height":60,"fontSize":48,"color":"#000000","bold":true,"anchorY":0,"anchorX":0,"align":"center"},"compId":7},{"type":"Image","props":{"y":12,"x":63,"width":60,"name":"icon","height":60},"compId":8},{"type":"Label","props":{"y":25,"x":135,"width":200,"text":"nickName","name":"nickName","height":40,"fontSize":32,"color":"#000000","align":"left"},"compId":9},{"type":"Label","props":{"y":25,"x":360,"width":200,"text":"1234567890","name":"bestScore","height":40,"fontSize":32,"color":"#000000","anchorY":0,"anchorX":0,"align":"left"},"compId":10}]}]}],"loadList":["img/panelBK.png"],"loadList3D":[]};
		return RankUI;
	})(View);
export {ui as default};