/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ActorScript from "./scripts/ActorScript"
import MainSceneScript from "./scripts/MainSceneScript"
import MatchScene from "./scripts/MatchScene"
import StartScene from "./scripts/StartScene"
import BulletScript from "./scripts/BulletScript"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/ActorScript.js",ActorScript);
		reg("scripts/MainSceneScript.js",MainSceneScript);
		reg("scripts/MatchScene.js",MatchScene);
		reg("scripts/StartScene.js",StartScene);
		reg("scripts/BulletScript.js",BulletScript);
    }
}
GameConfig.width = 1280;
GameConfig.height = 720;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "top";
GameConfig.alignH = "center";
GameConfig.startScene = "Start.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
