/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainScene from "./script/MainScene"
import BowScript from "./script/BowScript"
import MainSceneControl from "./script/MainSceneControl"
import StartScene from "./script/StartScene"
import ArrowScript from "./script/ArrowScript"
import BallScript from "./script/BallScript"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/MainScene.js",MainScene);
		reg("script/BowScript.js",BowScript);
		reg("script/MainSceneControl.js",MainSceneControl);
		reg("script/StartScene.js",StartScene);
		reg("script/ArrowScript.js",ArrowScript);
		reg("script/BallScript.js",BallScript);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "center";
GameConfig.startScene = "startScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
